# Generated by Django 4.1.3 on 2022-12-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recien_nacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('cupo', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('genero', models.CharField(max_length=12)),
            ],
        ),
    ]
