# Generated by Django 4.1.3 on 2022-12-11 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recien_nacido',
            name='edad',
        ),
        migrations.CreateModel(
            name='Historial_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('estado', models.CharField(max_length=30)),
                ('medicamento', models.CharField(max_length=300)),
                ('via_alimentacion', models.CharField(max_length=30)),
                ('tipo_alimentacion', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('Rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recien_nacido')),
            ],
        ),
    ]
